apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: submit-queue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: submit-queue
    spec:
      containers:
      - name: submit-queue
        command:
        - /mungegithub
        - --dry-run=true
        - --token-file=$(TOKEN_FILE)
        - --pr-mungers=$(PR_MUNGERS)
        - --weak-stable-jobs=$(WEAK_STABLE_JOBS)
        - --required-contexts=$(REQUIRED_CONTEXTS)
        - --number-of-old-test-results=$(NUMBER_OF_OLD_TEST_RESULTS)
        - --http-cache-dir=$(HTTP_CACHE_DIR)
        - --test-owners-csv=$(TEST_OWNERS_CSV)
        - --repo-dir=$(REPO_DIR)
        image: gcr.io/google_containers/submit-queue:2016-05-24-86f86cd
        env:
          - name: TOKEN_FILE
            valueFrom:
              configMapKeyRef:
                name: flags
                key: token-file
          - name: PR_MUNGERS
            valueFrom:
              configMapKeyRef:
                name: flags
                key: pr-mungers
          - name: WEAK_STABLE_JOBS
            valueFrom:
              configMapKeyRef:
                name: flags
                key: weak-stable-jobs
          - name: REQUIRED_CONTEXTS
            valueFrom:
              configMapKeyRef:
                name: flags
                key: required-contexts
          - name: NUMBER_OF_OLD_TEST_RESULTS
            valueFrom:
              configMapKeyRef:
                name: flags
                key: number-of-old-test-results
          - name: HTTP_CACHE_DIR
            valueFrom:
              configMapKeyRef:
                name: flags
                key: http-cache-dir
          - name: TEST_OWNERS_CSV
            valueFrom:
              configMapKeyRef:
                name: flags
                key: test-owners-csv
          - name: REPO_DIR
            valueFrom:
              configMapKeyRef:
                name: flags
                key: repo-dir
        ports:
        - name: status
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
        volumeMounts:
        - mountPath: /etc/secret-volume
          name: secret-volume
        - mountPath: /gitrepos
          name: repo
        - mountPath: /cache
          name: cache-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: github-token
      - name: repo
        emptyDir: {}
      - name: cache-volume
        persistentVolumeClaim:
          claimName: submit-queue-cache
