kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: submit-queue-cache
  namespace: k8s-kubernetes-github-io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi