apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: docs-staging
  name: docs-staging-cache
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: docs-staging-cache
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: docs-staging
  name: docs-staging-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
