apiVersion: v1
kind: Service
metadata:
  labels:
    app: docs-staging
  name: kubernetes-sq-status
spec:
  ports:
  - name: status
    port: 80
    targetPort: status
  selector:
    app: submit-queue
    target-repo: kubernetes
  type: LoadBalancer
