apiVersion: v1
kind: Service
metadata:
  labels:
    app: docs-staging
  name: docs-staging
spec:
  ports:
  - name: status
    port: 80
    targetPort: status
  selector:
    app: docs-staging
  type: LoadBalancer
